name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install Docker Compose
      run: |
        Invoke-WebRequest -Uri https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-windows-x86_64.exe -OutFile C:\ProgramData\DockerDesktop\docker-compose.exe
        [Environment]::SetEnvironmentVariable("Path", "$env:Path;C:\ProgramData\DockerDesktop", [System.EnvironmentVariableTarget]::Machine)

    - name: Build and run containers with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
